# template
parameters:
- name: ModuleName
  type: string
- name: FailOnTestFailure
  type: boolean
  default: true

stages:
- stage: stage
  jobs:
    - job: job
      steps:
        - powershell: |
            gci env:
- template: stages/build-module.yml
  parameters:
    ModuleName: ${{ parameters.ModuleName }}
- template: stages/test-module.yml
  parameters:
    ModuleName: ${{ parameters.ModuleName }}
    FailOnTestFailure: ${{ parameters.FailOnTestFailure }}
# - template: stages/deploy-module-public.yml
#   parameters:
#     ModuleName: ${{ parameters.ModuleName }}
#     RepoPath: ${{ parameters.RepoPath }}
#     RepoName: ${{ parameters.RepoName }}
#     GitHubPAT: ${{ parameters.GitHubPAT }}
