parameters:
- name: DocsPath
  type: string
- name: Environment
  type: string
- name: BuildCondition
  type: string

jobs:
- deployment: ${{ parameters.Environment }}
  condition: ${{ parameters.BuildCondition }}
  dependsOn: build
  environment:
    name: ${{ parameters.Environment }}
    resourceType: VirtualMachine
  workspace:
    clean: all
  strategy:
    rolling:
      deploy:
        steps:
          - task: DeleteFiles@1
            inputs:
              SourceFolder: $(Pipeline.Workspace)
              Contents: ${{ parameters.DocsPath }}
          - download: current
            artifact: ${{ parameters.DocsPath }}
          - task: CopyFiles@2
            inputs:
              SourceFolder: '$(Pipeline.Workspace)/${{ parameters.DocsPath }}'
              Contents: '**'
              TargetFolder: 'C:\inetpub\wwwroot\${{ parameters.DocsPath }}'
              CleanTargetFolder: true
