# template
parameters:
- name: DocsPath
  type: string
- name: CleanDestination
  type: boolean
  default: true
- name: ArtifactName
  type: string
  default: ''

jobs:
- job: build
  steps:
  # - script: |
  #     sudo npm i -g markdownlint-cli
  #     markdownlint "**/*.md"
  #   continueOnError: true
  #   displayName: Run Markdownlint
  - script: |
      git clone https://github.com/FISHMANPET/markdownlint-cli.git --single-branch --branch junit "$(Agent.BuildDirectory)/markdownlint-cli"
      pushd "$(Agent.BuildDirectory)/markdownlint-cli"
      npm install
      popd
      node "$(Agent.BuildDirectory)/markdownlint-cli/markdownlint.js" -j "$(Common.TestResultsDirectory)/Test-$(Build.SourceVersion).xml" "**/*.md"
    displayName: Markdown Lint
    continueOnError: true
  - task: PublishTestResults@2
    displayName: Publish Test Results
    inputs:
      testResultsFormat: JUnit
      testResultsFiles: '$(Common.TestResultsDirectory)/Test-$(Build.SourceVersion).xml'
      failTaskOnFailedTests: false
  - script: |
      docker pull squidfunk/mkdocs-material
      docker run --rm -v ${PWD}:/docs -v $(Build.ArtifactStagingDirectory):/docs/site squidfunk/mkdocs-material build
    displayName: mkdocs-material build
  - publish: $(Build.ArtifactStagingDirectory)
    artifact: ${{ coalesce(parameters.ArtifactName, parameters.DocsPath) }}
- template: deploy-docs.yml
  parameters:
    DocsPath: ${{ parameters.DocsPath }}
    CleanDestination: ${{ parameters.CleanDestination }}
    ArtifactName: ${{ coalesce(parameters.ArtifactName, parameters.DocsPath) }}
    Environment: Dev
    BuildCondition: and(succeeded(), startsWith(variables['build.sourceBranch'], 'refs/heads/dev'))
- template: deploy-docs.yml
  parameters:
    DocsPath: ${{ parameters.DocsPath }}
    CleanDestination: ${{ parameters.CleanDestination }}
    ArtifactName: ${{ coalesce(parameters.ArtifactName, parameters.DocsPath) }}
    Environment: Tst
    BuildCondition: and(succeeded(), not(startsWith(variables['build.sourceBranch'], 'refs/heads/dev')))
- template: deploy-docs.yml
  parameters:
    DocsPath: ${{ parameters.DocsPath }}
    CleanDestination: ${{ parameters.CleanDestination }}
    ArtifactName: ${{ coalesce(parameters.ArtifactName, parameters.DocsPath) }}
    Environment: Prd
    BuildCondition: and(succeeded(), eq(variables['build.sourceBranch'], 'refs/heads/master'))
